# Generated by Django 2.1.1 on 2018-09-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
    ]
