# Generated by Django 2.1.1 on 2018-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0008_auto_20180915_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_special_client',
            field=models.BooleanField(default=False, help_text='Tick to mark as a special client.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='administrator',
            field=models.BooleanField(default=False, help_text='Tick to give access to the admin page.'),
        ),
    ]
