# Generated by Django 2.1.1 on 2018-09-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0011_remove_employee_some_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='administrator',
            field=models.BooleanField(default=False, help_text='Tick to give access to the admin page.'),
        ),
    ]
