# Generated by Django 2.1.1 on 2018-09-18 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0012_employee_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('picture', models.ImageField(default='defaults/actor_image.png', upload_to='actors')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('duration', models.DurationField()),
                ('rating', models.FloatField()),
                ('release_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_principal_actor', models.BooleanField(default=False)),
                ('role_played_description', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaCore.Actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaCore.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/user.png', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='actor',
            name='members',
            field=models.ManyToManyField(through='CinemaCore.MovieCrew', to='CinemaCore.Movie'),
        ),
    ]
