# Generated by Django 2.1.1 on 2018-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0013_auto_20180918_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='members',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='CinemaCore.MovieCrew', to='CinemaCore.Actor'),
        ),
    ]
