# Generated by Django 2.1.1 on 2018-09-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0016_auto_20180919_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
    ]
