# Generated by Django 2.1.1 on 2018-09-22 23:55

import CinemaCore.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0017_remove_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_date',
            field=models.DateTimeField(default=CinemaCore.utils.utils.default_expiration_delta, editable=False),
        ),
    ]
