# Generated by Django 2.1.1 on 2018-09-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0018_auto_20180922_2355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'actor')},
        ),
    ]
