# Generated by Django 2.1.1 on 2018-10-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0019_auto_20180923_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(max_length=3, unique=True)),
                ('capacity', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MovieFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('cinema_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaCore.CinemaRoom')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaCore.Movie')),
            ],
        ),
    ]
