# Generated by Django 2.1.1 on 2018-10-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0020_cinemaroom_moviefunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='room_id',
            field=models.IntegerField(unique=True),
        ),
    ]
