# Generated by Django 2.1.1 on 2018-10-12 19:18

from django.db import migrations
from CinemaCore.utils.utils import unique_slug_generator


def generate_slug_for_movies(apps, schema_editor):
    '''
    We can't import the Movie model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Movies = apps.get_model('CinemaCore', 'Movie')
    for movie in Movies.objects.all():
        movie.slug = unique_slug_generator(movie)
        movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaCore', '0021_auto_20181012_1910'),
    ]

    operations = [
        migrations.RunPython(generate_slug_for_movies),
    ]
